# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - shortfin - SDXL

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci-sdxl.yaml'
      - 'shortfin/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-sdxl.yaml'
      - 'shortfin/**'

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
  IREE_REPO_DIR: ${{ github.workspace }}/iree
  LIBSHORTFIN_DIR: ${{ github.workspace }}/shortfin/

jobs:
  install-and-test:
    name: Install and test
    runs-on: linux-mi300-1gpu-ossci

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install dependencies
      run: |
        if dpkg -s cmake &>/dev/null; then
          echo 'cmake is installed'
        else
          sudo apt install cmake -y
        fi
        if dpkg -s ninja-build &>/dev/null; then
          echo 'ninja is installed'
        else
          sudo apt install ninja -y
        fi

    - name: Setup Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install requirements
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        pip install -r requirements-tests.txt
        pip install -r ../requirements-iree-pinned.txt
        pip freeze

    - name: Install shortfin
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      run: |
        pip install --no-compile -e .

    - name: Test apps/sd/e2e_test
      working-directory: ${{ env.LIBSHORTFIN_DIR }}
      env:
        HIP_VISIBLE_DEVICES: 0
      run: |
        pytest tests/apps/sd/e2e_test.py -v -s --system=amdgpu
